config/routes.rb
Rytp::Application.routes.draw do
  match 'auth/:provider/callback', :to => 'sessions#create'
  match 'auth/failure', :to => 'sessions#failure'
  match 'auth/logout', :to => 'sessions#destroy', :as => :logout

  resources :admin, :except => [:new, :create] do
    member do
      delete :poops
      delete :votes
    end
  end
  match 'admin' => 'admin#index'

  resources :news
  resources :contests

  match 'profile/:id' => 'users#show', :as => :profile, :via => :get
  resources :users, :only => [:edit, :update], :path => 'profile'

  match 'search' => 'poops#search', :as => :search
  match 'rytpmv' => 'poops#rytpmv', :as => :rytpmv
  match 'top/:category(/:period)' => 'poops#top', :as => :top

  post ':id/approve' => 'poops#approve', :as => :approve

  post ':id/reject' => 'poops#reject', :as => :reject

  match ':id' => 'poops#show', :as => :watch, :constraints => { :id => /\d+.*/ }

  match 'add_poop' => 'poops#new', :as => :add_poop
  match 'not_approved' => 'poops#not_approved', :as => :not_approved

  post 'vote/positive/:id', :to => 'votes#positive', :as => :vote_positive
  post 'vote/negative/:id', :to => 'votes#negative', :as => :vote_negative

  post 'favourites/add/:id', :to => 'favourites#add', :as => :add_to_favourites
  post 'favourites/remove/:id', :to => 'favourites#remove', :as => :remove_from_favourites

  resources :poops, :except => :new

  match 'wiki' => 'static#wiki', :as => :wiki
  match 'rules' => 'static#rules', :as => :rules
  match 'howto' => 'static#howto', :as => :howto
  match 'info' => 'static#info', :as => :info
  match 'files' => 'static#files', :as => :files

  match 'feed' => 'feed#index', :as => :rss_feed
  match 'feed/:category' => 'feed#poops', :as => :poops_feed
  match 'sitemap' => 'feed#sitemap', :as => :sitemap

  root :to => "poops#index"

end

app/models/poop.rb
require 'hpricot'

class Poop < ActiveRecord::Base
  attr_accessible :title, :description, :code, :category_id, :contest_id

  PAGINATES_PER = 5

  paginates_per PAGINATES_PER

  belongs_to :category
  belongs_to :contest
  belongs_to :user, :counter_cache => true

  has_many :positive_votes, :class_name => "Vote", :conditions => {:positive => true}
  has_many :negative_votes, :class_name => "Vote", :conditions => {:positive => false}
  has_many :votes, :dependent => :destroy

  has_many :favourites, :dependent => :destroy

  validates_presence_of :title
  validates_inclusion_of :category_id, :in => Category.ids
  validate :code_safe?

  before_validation :prepare_code
  before_save 'self.code = self.code.to_html'

  def prepare_code
    self.code = Hpricot.parse(self.code)
    self.code.search("*").collect!{ |node| node if node.name !~ /^iframe$/ }.compact.remove
  end

  def code_safe?
    iframes = (self.code/"iframe")
    src = iframes.first[:src] unless iframes.empty?

    errors.add(:code, I18n.t(:'wrong_code')) unless
        src =~ /^http\:\/\/(www\.)?(vk\.com|vkontakte\.ru|youtube\.com)/ and iframes.size == 1
  end

  scope :not_participating_now, joins('LEFT OUTER JOIN contests ON contests.id = poops.contest_id').
                                where('poops.contest_id IS NULL OR contests.end_at < ?', Date.today)
  scope :by_category, lambda { |category| where(:category_id => Category.find_all_by_name(category)) }
  scope :by_category_id, lambda { |category_id| where(:category_id => category_id) }
  scope :without_contest, where(:contest_id => nil)
  scope :with_contest, where('contest_id > 0')
  scope :ordered, order('created_at DESC')
  scope :back_ordered, order('created_at ASC')
  scope :only_approved, where(:approved => true)
  scope :approved, only_approved.not_participating_now
  scope :not_approved, where(:approved => false)
  scope :rated, limit(50)
  scope :popular, approved.rated
  scope :feed, lambda { |category| ordered.approved.by_category(category || 'RYTP') }
  scope :top_by_category_and_period, lambda { |category, period| by_category(category || 'RYTP').by_period(period || '').popular.not_participating_now }

  default_scope includes(:category, :user)

  delegate :name, :to => :category, :prefix => true, :allow_nil => true

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def self.top(category, period, page)
    Kaminari.paginate_array(Poop.top_by_category_and_period(category, period).to_a).page(page).per(PAGINATES_PER)
  end

  def self.search(text)
    return scoped unless text
    t = build_search_conditions(text, :title)
    d = build_search_conditions(text, :description)
    where((t[:query] + d[:query]) * ' OR ', *[t[:values] + d[:values]].flatten)
  end

  def self.fetch_last
    by_category('RYTP').approved.limit(1).last
  end

  def self.by_period(period)
    start = case period
            when 'by_month'
              1.month.ago
            when 'all_time'
              10.years.ago
            else
              1.week.ago
            end

    select('poops.*, count(votes.id) as vc').
    joins(:votes).
    where(:votes => {:created_at => start..Time.now}).
    group(Poop.columns.map{|c| "poops.#{c.name}"} * ', ').
    order('poops.rating DESC, vc DESC')
  end

  def self.poops_from_category(category_id)
    approved.by_category_id(category_id).back_ordered
  end

  def self.new_unapproved
    not_approved.count
  end

  def name
    "#{rating} - #{title}"
  end

  private

  def self.build_search_conditions(text, field)
    words = text.split(/[\s,\.\/\\\|\[\]\-_=\+{}\?\(\)]/).compact.select { |word| word.length >= 3 }
    { :query => Array.new(words.size).fill("poops.#{field} ILIKE ?"), :values => words.map{|t| "%#{t}%"} }
  end
end

app/controllers/poops_controller.rb
class PoopsController < ApplicationController
  before_filter :require_authentication, :except => [:index, :search, :top, :rytpmv, :show]
  before_filter :find_poop, :except => [:index, :rytpmv, :not_approved, :top, :search]
  before_filter :set_feed_class, :only => [:top, :search, :not_approved]

  authorize_resource

  def index
    redirect_to watch_path(last_poop), :status => :found if last_poop
  end

  def rytpmv
    poop = Poop.by_category('RYTPMV').approved.last

    if poop
      redirect_to watch_path(poop), :status => :found
    else
      render 'poops/index'
    end
  end

  def not_approved
    @poops = Poop.not_approved.ordered.page params[:page]

    respond_to do |format|
      format.html
      format.js { render 'shared/update_page', :layout => false, :locals => {:poops => @poops} }
    end
  end

  def approve
    @poop.approved = true

    flash[:success] = t(:'poop.approve') if @poop.save

    @poops = Poop.not_approved.ordered.page params[:page]

    respond_to do |format|
      format.html { redirect_to not_approved_path }
      format.js {
        if request.referer =~ /[^=]\d+\-[^\/]*$/
          render 'shared/update_poop', :layout => false, :locals => {:poop => @poop}
        else
          render 'shared/update_page', :layout => false, :locals => {:poops => @poops, :ajax => true}
        end
      }
    end
  end

  def reject
    @poop.contest = nil
    @poop.save

    flash[:notice] = t(:'contest.poop_rejected')

    respond_to do |format|
      format.html { redirect_to request.referer }
      format.js { render 'shared/update_poop', :layout => false, :locals => { :poop => @poop } }
    end
  end

  def search
    @poops = Poop.approved.search(params[:search]).page params[:page]

    respond_to do |format|
      format.html
      format.js { render 'shared/update_page', :layout => false, :locals => {:poops => @poops} }
    end
  end

  def top
    @poops = Poop.top(params[:category], params[:period], params[:page])

    respond_to do |format|
      format.html
      format.js { render 'shared/update_page', :layout => false, :locals => {:poops => @poops} }
    end
  end

  def show
    render_404 if (!@poop.approved? or @poop.contest.try(:active?)) and cannot?(:approve, @poop)
  end

  def new
  end

  def edit
  end

  def create
    @poop = current_user.poops.build
    @poop.accessible = :all if can?(:manage, @poop)
    @poop.attributes = params[:poop]

    if @poop.save
      redirect_to watch_path(last_poop), :notice => t(:'poop.added')
    else
      render :new
    end
  end

  def update
    @poop.accessible = :all if can?(:manage, @poop)

    if @poop.update_attributes(params[:poop])
      redirect_to watch_path(@poop)
    else
      render :edit
    end
  end

  def destroy
    flash[:deleted] = t(:'poop.deleted') if @poop.destroy

    respond_to do |format|
      format.html { redirect_to request.referer }
      format.js { render :text => "window.location.reload();" }
    end
  end

  private

  def find_poop
    @poop ||= if params[:id]
      Poop.find(params[:id])
    else
      Poop.new(params[:poop])
    end
  end

  def poop
    @poop
  end
  helper_method :poop

  def poops
    @poops
  end
  helper_method :poops
end

app/helpers/poops_helper.rb
module PoopsHelper
  def video(code)
    raw(sanitize code, :tags => %w{iframe}, :attributes => %w{src})
  end

  def random_poop(poop)
    poops = poops_from_category(poop.category_id)
    poops ? poops.at(rand(poops.count - 1)) : last_poop
  end

  def previous_poop(poop)
    poops = poops_from_category(poop.category_id)
    poops.any? ? poops.at((poops.index(poop) || 0) - 1) : last_poop
  end

  def next_poop(poop)
    poops = poops_from_category(poop.category_id)
    pos = poops.index(poop) || 0
    poops.any? ? poops.at(pos == (poops.count - 1) ? 0 : pos + 1) : last_poop
  end
end

app/views/poops/_form.html.haml
= form_for poop, :html => {:class => 'poop_form'} do |f|
  - if poop.errors.any?
    .error_explanation
      %h2
        = errors_count poop.errors.count
      %ul
        - poop.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :title, :placeholder => t(:'poop.title'), :title => t(:'poop.title'), :required => true, :autofocus => true
  .field.new_description
    = f.text_area :description, :placeholder => t(:'poop.description'), :title => t(:'poop.description')
  .field.new_code
    = link_to 'Как получить код видео?', howto_path, :target => '_blank'
    %br/
    = f.text_area :code, :placeholder => t(:'poop.code'), :title => t(:'poop.code'), :required => true
  .field
    = f.label :category_id
  .field
    = f.collection_select :category_id, all_categories, :id, :name, :prompt => 'Выберите из списка'
  - if active_contests.any?
    .field
      = f.label :contest_id
    .field
      = f.collection_select :contest_id, active_contests, :id, :name, {:include_blank => 'Выберите из списка'}
  - if can?(:approve, poop)
    .field
      = f.label :approved
      = f.check_box :approved
  .field
    Нажимая "Отправить", вы соглашаетесь с
    = link_to 'правилами', rules_path, :target => '_blank'
  .actions
    = f.submit 'Отправить', :class => :button

app/views/poops/_poop.html.haml
.poop{ :id => ["poop", poop.id] }
  %h1.title{ :title => "#{poop.title} | #{poop.category_name}" }
    = poop.title.truncate 30
  .video
    = video poop.code
  .info
    = render 'poops/poop_info', :poop => poop
  .wrapper
    .author
      - if poop.contest_id.nil? or !poop.contest.try(:active?)
        = t(:by) + ': '
        = poop.user ? link_to(poop.user, profile_path(poop.user)) : 'noname'
    .description_link
      - if poop.description.present?
        = link_to '#', :class => :button do
          %span.book.icon
          описание
      - else
        &nbsp;
    .description.hide
      = with_brs poop.description
    = render 'like_buttons/all' if current_page?(watch_path poop)

app/views/poops/_poop_info.html.haml
.rating
  = poop.rating.to_s + ' ' + t(:'rating', :count => poop.rating.abs)
.links
  - if current_user and current_user.favoured?(poop)
    = link_to remove_from_favourites_path(poop), :method => :post, :remote => true, :class => :button do
      %span.cross.icon
      удалить из избранного
  - else
    = link_to add_to_favourites_path(poop), :method => :post, :remote => true, :class => :button do
      %span.heart.icon
      добавить в избранное
  = link_to vote_positive_path(poop), :method => :post, :remote => true, :class => :button do
    %span.kosar.icon
    дать косарь
  = link_to vote_negative_path(poop), :method => :post, :remote => true, :class => :button do
    %span.xunta.icon
    xynta
  - if poop.contest_id.nil? or !poop.contest.try(:active?)
    = comments_link poop
  .admin_links
    - if can?(:reject, poop) and poop.contest_id.present?
      = link_to reject_path(poop), :method => :post, :remote => true, :class => :button do
        %span.cross.icon
        отменить участие в конкурсе (#{poop.contest})
    - if can?(:approve, poop) and !poop.approved?
      = link_to approve_path(poop), :method => :post, :remote => true, :class => :button do
        %span.check.icon
        подтвердить
    - if can?(:edit, poop)
      = link_to [:edit, poop], :class => :button do
        %span.pen.icon
        редактировать
    - if can?(:destroy, poop)
      = link_to poop, :remote => true, :class => :button, :method => :delete, :confirm => 'Вы уверены?' do
        %span.cross.icon
        удалить

app/views/poops/edit.html.haml
= set_title :title => 'редактирование пупа'
%h1 Редактирование Poop'a
= render 'form'
= link_to 'перейти к просмотру', watch_path(poop)

app/views/poops/index.html.haml
= set_title :type => ('RYTPMV' if current_page?(rytpmv_path))
= empty

app/views/poops/new.html.haml
= set_title :title => 'добавить poop'
%h1 Добавить Poop
= render 'form'

= content_for :ad_block_1 do
  = render '/ad/before_footer'

app/views/poops/not_approved.html.haml
= set_title :title => 'не подтвержденные'

.poops= render poops
= paginate poops
= empty if poops.empty?

= content_for :left do
  = render '/ad/left_skyscraper'

= content_for :right do
  = render '/ad/right_skyscraper'

= content_for :ad_block_1 do
  = render '/ad/before_footer'

app/views/poops/search.html.haml
= set_title :title => 'поиск'
.poops= render poops
= paginate poops
= empty if poops.empty?

= content_for :left do
  = render '/ad/left_skyscraper'

= content_for :right do
  = render '/ad/right_skyscraper'

= content_for :ad_block_1 do
  = render '/ad/before_footer'

app/views/poops/show.html.haml
= set_title :type => poop.category_name, :title => poop.title
= set_description poop.description.truncate(100)
.poop= render poop

= content_for :comments do
  #vk_comments
    :javascript
      VK.Widgets.Comments("vk_comments", {limit: 10, width: "496", pageUrl: "http://rytp.ru/#{poop.id}"});

= content_for :left do
  .nav_left
    = link_to image_tag('controls/previous.png', :width => 19, :height => 22, :alt => '<'), watch_path(previous_poop poop), :id => :previous, :rel => :prefetch

= content_for :right do
  .nav_right
    = link_to image_tag('controls/next.png', :width => 19, :height => 22, :alt => '>'), watch_path(next_poop poop), :id => :next, :rel => :prefetch
    = link_to image_tag('controls/random.png', :width => 18, :height => 47, :alt => 'R'), watch_path(random_poop poop), :id => :random

= content_for :ad_block_1 do
  = render '/ad/before_comments'

app/views/poops/top.html.haml
= set_title :type => params[:category], :title => 'топ'

.categories
  %h1.rytp= link_to_active 'RYTP', top_path(:RYTP, params[:period])
  %h1.rytpmv= link_to_active 'RYTPMV', top_path(:RYTPMV, params[:period])
.periods
  = link_to_active 'за неделю', top_path(params[:category], nil), :class => 'by_week'
  = link_to_active 'за месяц', top_path(params[:category], 'by_month'), :class => 'by_month'
  = link_to_active 'за все время', top_path(params[:category], 'all_time'), :class => 'all_time'

.poops= render poops
= paginate poops
= empty if poops.empty?

= content_for :left do
  = render '/ad/left_skyscraper'

= content_for :right do
  = render '/ad/right_skyscraper'

= content_for :ad_block_1 do
  = render '/ad/before_footer'