config/routes.rb
Rytp::Application.routes.draw do
  match 'auth/:provider/callback', :to => 'sessions#create'
  match 'auth/failure', :to => 'sessions#failure'
  match 'auth/logout', :to => 'sessions#destroy', :as => :logout

  resources :admin, :except => [:new, :create] do
    member do
      delete :poops
      delete :votes
    end
  end
  match 'admin' => 'admin#index'

  resources :news
  resources :contests

  match 'profile/:id' => 'users#show', :as => :profile, :via => :get
  resources :users, :only => [:edit, :update], :path => 'profile'

  match 'search' => 'poops#search', :as => :search
  match 'rytpmv' => 'poops#rytpmv', :as => :rytpmv
  match 'top/:category(/:period)' => 'poops#top', :as => :top

  post ':id/approve' => 'poops#approve', :as => :approve

  post ':id/reject' => 'poops#reject', :as => :reject

  match ':id' => 'poops#show', :as => :watch, :constraints => { :id => /\d+.*/ }

  match 'add_poop' => 'poops#new', :as => :add_poop
  match 'not_approved' => 'poops#not_approved', :as => :not_approved

  post 'vote/positive/:id', :to => 'votes#positive', :as => :vote_positive
  post 'vote/negative/:id', :to => 'votes#negative', :as => :vote_negative

  post 'favourites/add/:id', :to => 'favourites#add', :as => :add_to_favourites
  post 'favourites/remove/:id', :to => 'favourites#remove', :as => :remove_from_favourites

  resources :poops, :except => :new

  match 'wiki' => 'static#wiki', :as => :wiki
  match 'rules' => 'static#rules', :as => :rules
  match 'howto' => 'static#howto', :as => :howto
  match 'info' => 'static#info', :as => :info
  match 'files' => 'static#files', :as => :files

  match 'feed' => 'feed#index', :as => :rss_feed
  match 'feed/:category' => 'feed#poops', :as => :poops_feed
  match 'sitemap' => 'feed#sitemap', :as => :sitemap

  root :to => "poops#index"

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  attr_accessible :name, :description, :start_at, :end_at, :first_place, :second_place, :third_place

  PAGINATES_PER = 5

  paginates_per PAGINATES_PER

  has_many :poops

  validates_presence_of :name, :description
  validate :validate_dates

  scope :active, where('contests.start_at <= ?', Date.today)
  scope :active_now, active.where('contests.end_at >= ?', Date.today)

  default_scope order('end_at DESC').includes(:poops)

  def to_s
    name
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def validate_dates
    errors.add(:end_at, I18n.t(:'contest.wrong_dates')) if start_at >= end_at
  end

  def self.fetch_last
    active.limit(1).first
  end

  def approved_poops(admin=false)
    Poop.unscoped do
      if admin
        poops
      else
        poops.only_approved
      end
    end
  end

  def first_winner
    Poop.find first_place if first_place?
  end

  def second_winner
    Poop.find second_place if second_place?
  end

  def third_winner
    Poop.find third_place if third_place?
  end

  def active?
    start_at <= Date.today and end_at >= Date.today
  end

  def has_poops?
    poops.count > 0
  end

  def completed?
    end_at < Date.today
  end

  def has_winners?
    %w{first_place second_place third_place}.any? {|e| eval("#{e}?") }
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_filter :require_authentication, :except => [:index, :show]

  authorize_resource

  def index
    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.js { render 'shared/update_page', :layout => false, :locals => { :poops => poops, :id => params[:id] } }
    end
  end

  def new
  end

  def edit
  end

  def create
    if contest.save
      redirect_to contest, :notice => t(:'contest.created')
    else
      render :new
    end
  end

  def update
    if contest.update_attributes(params[:contest])
      redirect_to contest, :notice => t(:'contest.updated')
    else
      render :edit
    end
  end

  def destroy
    contest.destroy

    redirect_to contests_path, :notice => t(:'contest.deleted')
  end

  private

  def contest
    @contest ||= if params[:id]
      Contest.find(params[:id])
    else
      Contest.new(params[:contest])
    end
  end
  helper_method :contest

  def contests
    @contests ||= if can?(:manage, Contest)
      Contest.scoped
    else
      Contest.active
    end.page params[:page]
  end
  helper_method :contests

  def poops
    return @poops if @poops

    @poops = Poop.unscoped do
      contest.poops.order('created_at DESC')
    end

    @poops = @poops.only_approved if cannot?(:reject, Poop)
    @poops = @poops.page params[:page]
  end
  helper_method :poops
end

app/views/contests/_contest.html.haml
.contest.one
  %h2.title= contest.name
  %div{ :class => ['dates', (contest.active? ? 'active' : nil)] * ' ' }
    %time.start_at= russian_date(contest.start_at)
    %label &mdash;
    %time.end_at= russian_date(contest.end_at)
  .clear
  .description= sanitize(contest.description, :tags=>[]).truncate(300)
  .actions
    - if can?(:manage, contest)
      = link_to 'изменить', [:edit, contest]
      = link_to 'удалить', contest, :confirm => 'Вы уверены?', :method => :delete
  = link_to 'перейти к просмотру', contest, :class => 'cut'
  .clear

app/views/contests/_form.html.haml
= form_for contest do |f|
  -if contest.errors.any?
    .error_explanation
      %h2
        = errors_count contest.errors.count
      %ul
        - contest.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name, :placeholder => t(:'contest.name'), :class => :title, :required => true
  .field
    - redactor("#contest_body")
    - redactor_css
    = f.text_area :description, :id => :contest_body
  .field
    = f.label :start_at
  .field
    = f.date_select :start_at
  .field
    = f.label :end_at
  .field
    = f.date_select :end_at
  - if contest.has_poops? and contest.completed?
    .field
      = f.label :first_place
    .field
      = f.collection_select :first_place, contest.poops, :id, :name, {:include_blank => 'Выберите из списка'}
    .field
      = f.label :second_place
    .field
      = f.collection_select :second_place, contest.poops, :id, :name, {:include_blank => 'Выберите из списка'}
    .field
      = f.label :third_place
    .field
      = f.collection_select :third_place, contest.poops, :id, :name, {:include_blank => 'Выберите из списка'}
  .actions
    = f.submit 'сохранить'

app/views/contests/edit.html.haml
= set_title :title => 'редактирование конкурса'

.contests
  = render 'form'

  = link_to 'назад', contests_path

app/views/contests/index.html.haml
= set_title :title => 'конкурсы'

.all_contests
  .contests_list
    - if contests.any?
      = render contests
    - else
      Пока нет ни одного конкурса
  = paginate contests

= content_for :ad_block_1 do
  = render '/ad/before_footer'

app/views/contests/index.js.erb
$('.contests_list').html("<%= escape_javascript(render contests) %>");

$('.pagination').replaceWith("<%= escape_javascript(paginate contests) %>");

app/views/contests/new.html.haml
= set_title :title => 'добавить конкурс'

.contests
  %h1 Добавить конкурс
  = render 'form'

  = link_to 'назад', contests_path

app/views/contests/show.html.haml
= set_title :title => contest.name
= set_description sanitize(contest.description, :tags => []).truncate(100)
.contests
  .contest
    %h1.title
      = contest.name
    .content.redactor
      %article= raw contest.description
    .actions
      - if can?(:manage, contest)
        = link_to 'изменить', [:edit, contest]
        = link_to 'удалить', contest, :confirm => 'Вы уверены?', :method => :delete
    %div{ :class => ['dates', (contest.active? ? 'active' : nil)] * ' ' }
      %time.start_at= russian_date(contest.start_at)
      %label &mdash;
      %time.end_at= russian_date(contest.end_at)
    = render 'like_buttons/all'
    - if contest.active?
      .statistics
        Участвует #{contest.approved_poops(can?(:reject, Poop)).count} #{t :poops, :count => contest.approved_poops(can?(:reject, Poop)).count}
    - elsif contest.start_at > Date.today
      .statistics
        Конкурс еще не начался
    - else
      .statistics
        Конкурс завершен
      - if contest.has_winners?
        .winners
          %h2 Победители:
          .list
            - if contest.first_place
              %h3 Первое место: #{link_to contest.first_winner.user, profile_path(contest.first_winner.user)}
              .poop
                .video= video contest.first_winner.code
            - if contest.second_place
              %h3 Второе место: #{link_to contest.second_winner.user, profile_path(contest.second_winner.user)}
              .poop
                .video= video contest.second_winner.code
            - if contest.third_place
              %h3 Третье место: #{link_to contest.third_winner.user, profile_path(contest.third_winner.user)}
              .poop
                .video= video contest.third_winner.code
        .clear
    .poops
      = render poops
    = paginate poops

= content_for :comments do
  #vk_comments
    :javascript
      VK.Widgets.Comments("vk_comments", {limit: 10, width: "496", pageUrl: "http://rytp.ru#{contest_path(contest)}"});

= content_for :ad_block_1 do
  = render '/ad/before_comments'