config/routes.rb
Rytp::Application.routes.draw do
  match 'auth/:provider/callback', :to => 'sessions#create'
  match 'auth/failure', :to => 'sessions#failure'
  match 'auth/logout', :to => 'sessions#destroy', :as => :logout

  resources :admin, :except => [:new, :create] do
    member do
      delete :poops
      delete :votes
    end
  end
  match 'admin' => 'admin#index'

  resources :news
  resources :contests

  match 'profile/:id' => 'users#show', :as => :profile, :via => :get
  resources :users, :only => [:edit, :update], :path => 'profile'

  match 'search' => 'poops#search', :as => :search
  match 'rytpmv' => 'poops#rytpmv', :as => :rytpmv
  match 'top/:category(/:period)' => 'poops#top', :as => :top

  post ':id/approve' => 'poops#approve', :as => :approve

  post ':id/reject' => 'poops#reject', :as => :reject

  match ':id' => 'poops#show', :as => :watch, :constraints => { :id => /\d+.*/ }

  match 'add_poop' => 'poops#new', :as => :add_poop
  match 'not_approved' => 'poops#not_approved', :as => :not_approved

  post 'vote/positive/:id', :to => 'votes#positive', :as => :vote_positive
  post 'vote/negative/:id', :to => 'votes#negative', :as => :vote_negative

  post 'favourites/add/:id', :to => 'favourites#add', :as => :add_to_favourites
  post 'favourites/remove/:id', :to => 'favourites#remove', :as => :remove_from_favourites

  resources :poops, :except => :new

  match 'wiki' => 'static#wiki', :as => :wiki
  match 'rules' => 'static#rules', :as => :rules
  match 'howto' => 'static#howto', :as => :howto
  match 'info' => 'static#info', :as => :info
  match 'files' => 'static#files', :as => :files

  match 'feed' => 'feed#index', :as => :rss_feed
  match 'feed/:category' => 'feed#poops', :as => :poops_feed
  match 'sitemap' => 'feed#sitemap', :as => :sitemap

  root :to => "poops#index"

end

app/views/admin/_form.html.haml
= form_for user, :url => admin_path(user), :html => { :method => :put } do |f|
  - if user.errors.any?
    .error_explanation
      %h2
        = errors_count user.errors.count
      %ul
        - user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
  .field
    = f.text_field :name
  .field
    = f.label :nickname
  .field
    = f.text_field :nickname
  .field
    = f.label :youtube_channel
  .field
    = f.text_field :youtube_channel
  .field
    = f.label :profile_url
  .field
    = f.text_field :profile_url
  .field
    = f.label :show_profile_url
  .field
    = f.check_box :show_profile_url
  .field
    = f.label :use_nickname_instead_of_name
  .field
    = f.check_box :use_nickname_instead_of_name
  .rules
    %h4= t(:'user.role')
    = role_selection(user)

  .actions
    = f.submit 'сохранить'

app/views/admin/index.html.haml
= set_title :title => 'администрирование пользователей'

.admin
  = form_tag admin_index_path, :remote => true do
    = text_field_tag 'search', params[:search], :class => :title, :id => :user_search
  .users
    = render users
  = paginate users

- content_for :bottom_javascript do
  = javascript_include_tag 'jquery.observe_field'
  :javascript
    $("#user_search").observe_field(0.5, function( ) {
      $(this).parent().submit();
    });

app/views/admin/index.js.erb
$('.users').html("<%= escape_javascript(render users) %>");

$('.pagination').replaceWith("<%= escape_javascript(paginate users) %>");

app/views/admin/show.html.haml
= set_title :title => 'администрирование пользователя'

.admin
  = render 'form'

  .delete
    %h4 Удалить
    .field
      = link_to "пользователя", admin_path(user), :method => :delete, :confirm => 'Вы уверены?'
    .field
      = link_to "пупы пользователя (#{user.poops.count})", poops_admin_path(user), :method => :delete, :confirm => 'Вы уверены?'
    .field
      = link_to "косари отданные пользователем (#{user.votes.count})", votes_admin_path(user), :method => :delete, :confirm => 'Вы уверены?'