config/routes.rb
Rytp::Application.routes.draw do
  match 'auth/:provider/callback', :to => 'sessions#create'
  match 'auth/failure', :to => 'sessions#failure'
  match 'auth/logout', :to => 'sessions#destroy', :as => :logout

  resources :admin, :except => [:new, :create] do
    member do
      delete :poops
      delete :votes
    end
  end
  match 'admin' => 'admin#index'

  resources :news
  resources :contests

  match 'profile/:id' => 'users#show', :as => :profile, :via => :get
  resources :users, :only => [:edit, :update], :path => 'profile'

  match 'search' => 'poops#search', :as => :search
  match 'rytpmv' => 'poops#rytpmv', :as => :rytpmv
  match 'top/:category(/:period)' => 'poops#top', :as => :top

  post ':id/approve' => 'poops#approve', :as => :approve

  post ':id/reject' => 'poops#reject', :as => :reject

  match ':id' => 'poops#show', :as => :watch, :constraints => { :id => /\d+.*/ }

  match 'add_poop' => 'poops#new', :as => :add_poop
  match 'not_approved' => 'poops#not_approved', :as => :not_approved

  post 'vote/positive/:id', :to => 'votes#positive', :as => :vote_positive
  post 'vote/negative/:id', :to => 'votes#negative', :as => :vote_negative

  post 'favourites/add/:id', :to => 'favourites#add', :as => :add_to_favourites
  post 'favourites/remove/:id', :to => 'favourites#remove', :as => :remove_from_favourites

  resources :poops, :except => :new

  match 'wiki' => 'static#wiki', :as => :wiki
  match 'rules' => 'static#rules', :as => :rules
  match 'howto' => 'static#howto', :as => :howto
  match 'info' => 'static#info', :as => :info
  match 'files' => 'static#files', :as => :files

  match 'feed' => 'feed#index', :as => :rss_feed
  match 'feed/:category' => 'feed#poops', :as => :poops_feed
  match 'sitemap' => 'feed#sitemap', :as => :sitemap

  root :to => "poops#index"

end

app/views/layouts/_admin_panel.html.haml
- if current_user and current_user.cached_roles.count > 1
  .admin_panel
    %ul.links
      - if can?(:manage, User)
        %li= link_to "админка", admin_index_path
      - if can?(:approve, Poop)
        %li= link_to "новых пупов (#{Poop.new_unapproved})", not_approved_path
      - if can?(:create, News)
        %li= link_to "добавить новость", new_news_path
      - if can?(:manage, Contest)
        %li= link_to "добавить конкурс", new_contest_path

app/views/layouts/_auth_block.html.haml
- if current_user
  %label.welcome= t(:'welcome')
  %ul.auth-links.welcome
    %li
      = link_to current_user, profile_path(current_user)
    %li
      = link_to t(:'sessions.destroy'), logout_path

-else
  %label.auth= t(:'sessions.new') + ':'
  %ul.auth-links.sign_in
    %li
      = link_to "Вконтакте", "/auth/vkontakte", :class => 'ir vkontakte', :title => 'Войти через ВКонтакте'
    %li
      = link_to "Twitter", "/auth/twitter", :class => 'ir twitter', :title => 'Войти через Twitter'
    %li
      = link_to "Facebook", "/auth/facebook", :class => 'ir facebook', :title => 'Войти через Facebook'
    %li.last
      = link_to "Google", "/auth/google", :class => 'ir google', :title => 'Войти через Google'

app/views/layouts/_counter.html.erb
<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t13.1;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров за 24"+
" часа, посетителей за 24 часа и за сегодня' "+
"border='0' width='88' height='31'><\/a>")//--></script><!--/LiveInternet-->

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => key }
      %p= value

app/views/layouts/_footer.html.haml
.container
  .before
    = yield :ad_block_1
  = yield :comments
  #sub_footer
    .icons
      .letsweb
        = link_to "letsweb.ru", "http://letsweb.ru", :class => :ir, :title => "letsweb.ru", :target => '_blank'
      .rytp
        = link_to "rytp.ru", "http://rytp.ru", :class => :ir, :title => "rytp.ru"
    .text
      %p
        %label RYTP.ru
        является наилучшим источником RYTP и RYTPMV.
      %p.last
        Сайт для любителей пупов, от
        = link_to "letsweb.ru", 'http://letsweb.ru', :target => '_blank'
      %p.established
        Основан в октябре 2010 года
    .counter
      = render 'layouts/counter'

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title
  == #{ title }

%meta{ :name => "description", :content => "#{description}" }/
%meta{ :name => "author", :content => "olancheg" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=1000, initial-scale=1" }/

-# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons
%link{ :rel => "shortcut icon", :href => "/favicon.ico" }/
%link{ :rel => "apple-touch-icon", :href => "/apple-touch-icon.png" }/
%link{ :rel => "sitemap", :type => "application/xml", :title => "Sitemap", :href => sitemap_path+'.xml' }/

-# RSS feed
= auto_discovery_link_tag(:rss, rss_feed_path+'.rss')

-# Pass in a stylesheet_partial to render inside your head
- if local_assigns[:stylesheet_partial]
  = render local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr and Respond.
-# Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
= javascript_include_tag 'modernizr.min', 'respond.min'

-# Vkontakte OpenAPI initialization
%script(type="text/javascript" src="http://userapi.com/js/api/openapi.js" charset="windows-1251")
:javascript
  VK.init({ apiId: 2021578, onlyWidgets: true })

-# Custom stylesheets in head
= yield :stylesheets

-# Custom javascript in head
= yield :javascripts

= csrf_meta_tag

app/views/layouts/_header.html.haml
.container
  .last_new
    %label Последняя новость:
    = link_to last_new.title.truncate(35), news_path(last_new) if last_new
  .contest
    - if last_contest
      = link_to last_contest do
        конкурс (#{last_contest.approved_poops(can?(:reject, Poop)).count})
    - else
      конкурсов пока нет
  .auth
    = render 'layouts/auth_block'

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery, with a protocol relative URL
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
-# remote_jquery and local_jquery helpers use minified jquery unless Rails.env is development
- if !google_api_key.blank?
  = javascript_include_tag "//www.google.com/jsapi?key=#{google_api_key}"
  :javascript
    google.load(#{ remote_jquery("1.6") });
- else
  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/#{ local_jquery("1.6") }"

-# fall back to local jQuery if necessary
:javascript
  window.jQuery || document.write("<script src='/javascripts/jquery.min.js'>\x3C/script>")

= javascript_include_tag :jquery_libs, :cache => 'jquery_libs'
= javascript_include_tag :app, :cache => 'app'

= yield :bottom_javascript

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[["_setAccount","#{google_account_id}"],["_trackPageview"],["_trackPageLoadTime"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));

= render 'layouts/yandex_metrika'

app/views/layouts/_menu.html.haml
%ul#menu
  %li
    = link_to t(:'menu.rytp'), root_path, :class => active?(:boolean => (defined?(poop) and poop and poop.category_name.try(:to_sym) == :RYTP))
  %li
    = link_to t(:'menu.rytpmv'), rytpmv_path, :class => active?(:boolean => (defined?(poop) and poop and poop.category_name.try(:to_sym) == :RYTPMV))
  %li
    = link_to t(:'menu.feed'), poops_feed_path(:RYTP), :class => active?(:path => [poops_feed_path(:RYTP), poops_feed_path(:RYTPMV)])
  %li
    = link_to t(:'menu.top'), top_path(:RYTP), :class => active?(:path => [nil, 'by_month', 'all_time'].map{|period| [top_path(:RYTP, period), top_path(:RYTPMV, period)] })
  %li
    = link_to t(:'menu.contest'), contests_path, :class => active?(:boolean => ( defined?(contest) or defined?(contests) ))

app/views/layouts/_small_menu.html.haml
%ul#small_menu
  %li
    = link_to t(:'menu.news'), news_index_path, :class => active?(:boolean => (controller_name == 'news'))
  %li
    = link_to t(:'menu.wiki'), wiki_path, :class => active?(:path => wiki_path)
  %li
    = link_to t(:'menu.files'), files_path, :class => active?(:path => files_path)
  %li
    = link_to t(:'menu.info'), info_path, :class => active?(:path => info_path)
  %li
    = link_to t(:'menu.add'), add_poop_path, :class => active?(:path => add_poop_path)

app/views/layouts/_social.html.haml
#social
  = link_to image_tag('twitter.png', :width => 53, :height => 37), 'http://twitter.com/rytpru', :target => '_blank', :title => 'Наш твиттер'
  = link_to image_tag('vk.png', :width => 53, :height => 37), 'http://vkontakte.ru/public23535228', :target => '_blank', :title => 'Паблик ВКонтакте'
  = link_to image_tag('rss.png', :width => 53, :height => 37), rss_feed_path+'.rss', :title => 'RSS лента'

app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'style', 'jquery.jgrowl', 'css3buttons', 'tipsy', 'redactor', :media => 'all', :cache => true

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/_yandex_metrika.html.erb
<!-- Yandex.Metrika counter -->
<div style="display:none;"><script type="text/javascript">
(function(w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter9448837 = new Ya.Metrika({id:9448837, enableAll: true, trackHash:true});
        }
        catch(e) { }
    });
})(window, "yandex_metrika_callbacks");
</script></div>
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
<noscript><div><img src="//mc.yandex.ru/watch/9448837" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    -# To render a different stylesheet partial inside the head (i.e. for admin layout)
    -# just copy _stylesheets.html.haml, and point to that partial instead.
    = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"

  %body
    #container
      = render "layouts/admin_panel"
      = render "layouts/flashes"

      #main{ :role => 'main' }
        %header#header
          = render "layouts/header"
        = render "layouts/navigation"

        .container.triangle
          %div{:class => [:content, @feed_class] * ' '}
            .left
              = yield :left
              .fix &nbsp;
            .middle
              = yield
            .right
              = yield :right
              .fix &nbsp;

        %footer#footer
          = render "layouts/footer"
        .clear

    -# Javascript at the bottom for fast page loading
    = render "layouts/javascripts"